// =====================================================================
// AUTO-GENERATED -- DO NOT EDIT.
// Generated by tools/codegen/jlp_codegen.py from protocol/jlp.yaml
// IDL hash: 08c74a3f4b7e843a
// =====================================================================

#pragma once

#include <cstdint>

namespace collider {
namespace pool {
namespace jlp_wire {

constexpr int PROTOCOL_VERSION = 4;

// JLP message header magic
constexpr char MAGIC[4] = {
    0x4b, 0x41, 0x4e, 0x47
};

enum class MessageType : uint8_t {
    AUTH = 0x01,
    AUTH_OK = 0x02,
    AUTH_FAIL = 0x03,
    WORK_REQ = 0x10,
    WORK_ASN = 0x11,
    DP_SUBMIT = 0x20,
    DP_ACK = 0x21,
    DP_BATCH = 0x22,
    DP_SUBMIT_V2 = 0x23,
    DP_BATCH_V2 = 0x24,
    DP_SUBMIT_V3 = 0x25,
    DP_BATCH_V3 = 0x26,
    STATS_REQ = 0x30,
    STATS_RSP = 0x31,
    CHALLENGE = 0x32,
    CHALLENGE_RSP = 0x33,
    SOLUTION = 0x40,
    PING = 0x50,
    PONG = 0x51,
    MAINTENANCE = 0x60,
    MSG_ERROR = 0xff,
};

// v1.4.2 B.5: MSG_ERROR payload codes
enum class ErrorCode : uint8_t {
    ok = 0x00,
    internal = 0x01,
    malformed_header = 0x02,
    malformed_payload = 0x03,
    payload_too_large = 0x04,
    unsupported_message_type = 0x05,
    protocol_version_mismatch = 0x10,
    auth_version_unsupported = 0x11,
    auth_clock_skew = 0x12,
    auth_nonce_reuse = 0x13,
    auth_bad_credentials = 0x14,
    work_id_mismatch = 0x20,
    dp_sequence_out_of_window = 0x21,
    dp_replay = 0x22,
    rate_limited = 0x30,
};

// Protocol constants
// 1 MB cap to prevent OOM
constexpr uint32_t MAX_MESSAGE_SIZE = 1048576;
// Max DPs per DP_BATCH or DP_BATCH_V2
constexpr uint32_t MAX_BATCH_SIZE = 10000;
// Worker must send AUTH within this window
constexpr uint32_t AUTH_TIMEOUT_SECS = 30;
// Client PING frequency
constexpr uint32_t KEEPALIVE_SECS = 20;
// Jumps per committed checkpoint (v1.5.4)
constexpr uint32_t CHECKPOINT_INTERVAL = 65536;
// Server-side allowed +/- skew on AuthPayloadV2.timestamp_ms
constexpr uint32_t AUTH_CLOCK_DRIFT_SECS = 30;

#pragma pack(push, 1)
// Every JLP message starts with this header. MAGIC + type + flags +
// payload_length. Total 8 bytes.
//
// v1.4.2 B.5: the `flags` byte (originally "Reserved, currently 0")
// now carries the protocol_version negotiated for the connection.
// Senders MUST set `flags == PROTOCOL_VERSION` (2 for v1.4.2, 3 for
// v1.5). Receivers that read `flags != PROTOCOL_VERSION` MUST respond
// MSG_ERROR with code 0x10 (protocol_version_mismatch). Old clients
// with flags=0 are detected as v0/legacy. This avoids a header layout
// break while making future rollforwards (DP_BATCH_V3, etc.) explicit.
//
// v1.5 (protocol_version=3): WORK_ASN payload grew by three fields
// (kangaroo_type, start_offset_a, start_offset_b) carrying the
// asymmetric tame-only / wild-only work assignment. SOLUTION is now
// strictly server-to-client (the pool server is the sole key-computer).
// v1.4.x clients are AUTH-gated out by the server's strict version
// check; they cannot reach the v1.5 work-assignment path.
struct Header {   // wire size 8 bytes
    uint8_t magic[4];   // Always "KANG"
    uint8_t type;   // MessageType enum
    uint8_t flags;   // v1.4.2 B.5: protocol_version (high 8 bits of nibble). Senders set to PROTOCOL_VERSION (2).
    uint16_t payload_size;   // Bytes following the header (little-endian)
};
static_assert(sizeof(Header) == 8, "Header must be 8 bytes");

// Worker authentication request (LEGACY v1, no replay protection).
// worker_name doubles as the BTC payout address; password is the
// optional pool password (zero-filled when none configured). Both
// fields null-padded.
//
// DEPRECATED in v1.4.2 in favour of AuthPayloadV2 which adds
// timestamp_ms + nonce for replay defence and clock-drift bounds.
// Clients must NOT send this struct; servers will reject.
struct AuthPayload {   // wire size 96 bytes
    uint8_t worker_name[64];   // UTF-8 worker name / BTC address, null-padded
    uint8_t password[32];   // Optional shared pool password, null-padded
};
static_assert(sizeof(AuthPayload) == 96, "AuthPayload must be 96 bytes");

// v1.4.2 worker authentication request. Adds timestamp_ms +
// nonce so the server can reject replays of captured AUTH packets
// and enforce client-clock drift bounds (default +/- 30 seconds).
//
// Matches src/pool/jlp_pool_client.hpp::JLPClientHelloV2 exactly.
// The handwritten C++ struct and the codegen-emitted struct have
// sizeof equality enforced by static_assert in
// tests/test_jlp_wire_generated.cpp (v1.4.2 B.3).
//
// Pre-v1.4.2 the wire-format-vs-IDL drift was the audit's most
// serious correctness finding: IDL said 96 bytes, client sent 120,
// handshake test asserted 76, and the drift detector did not
// cover AUTH at all.
struct AuthPayloadV2 {   // wire size 120 bytes
    uint8_t worker_name[64];   // UTF-8 worker name / BTC address, null-padded
    uint8_t password[32];   // Optional shared pool password, null-padded
    uint64_t timestamp_ms;   // Client wall-clock time in ms (LE); server enforces drift bound
    uint8_t nonce[16];   // Per-AUTH random nonce; server keeps a short-window seen-set to reject replays
};
static_assert(sizeof(AuthPayloadV2) == 120, "AuthPayloadV2 must be 120 bytes");

// v1.5.4 (protocol_version=4, additive): the AUTH_OK message, which was
// historically zero-payload, now carries this fixed advert.
//
// v1.5.5 (C3 fix): grew from 324 to 388 bytes with a trailing 64-byte
// manifest_sig. The signature is an Ed25519 detached signature over the
// CANONICAL UPDATE MANIFEST (see below). Without it a malicious or
// compromised pool could advertise download_url + sha256 of an arbitrary
// binary; the client would fetch it over valid TLS, the (attacker-chosen)
// hash would match, and the binary would be installed and relaunched with
// the operator's argv -> fleet-wide RCE. The client now verifies the
// signature against an Ed25519 PUBLIC key compiled into the binary BEFORE
// fetching anything, and refuses any manifest with a missing/invalid
// signature or a version that is not strictly newer than its own.
//
// CANONICAL UPDATE MANIFEST (signed byte string; client and server MUST
// build these bytes identically):
//
//   manifest = DOMAIN
//           || u16le(len(latest_version)) || latest_version
//           || u16le(len(min_version))    || min_version
//           || u16le(len(download_url))   || download_url
//           || sha256
//
// where:
//   * DOMAIN          = the 19 ASCII bytes "COLLIDER-UPDATE-v1\n"
//                       (domain separator; pins this signature to the
//                       update use so a signature minted for any other
//                       purpose cannot be replayed here).
//   * u16le(n)        = the unsigned 16-bit length of the following field,
//                       little-endian. Lengths are the UNPADDED string
//                       lengths (the wire fields are NUL-padded; the
//                       manifest uses the trimmed string up to the first
//                       NUL).
//   * latest_version,
//     min_version,
//     download_url     = the UNPADDED ASCII bytes (no trailing NULs).
//   * sha256          = the raw 32-byte SHA-256 (fixed length, no prefix).
//
// manifest_sig = Ed25519_sign(release_private_key, manifest). All zero
// (64 NUL bytes) means "no signature" -> the client refuses to update.
//
// Backward compatible in BOTH directions: a pre-v1.5.4 client reads
// header.payload_size and discards the bytes (its handle_auth_ok ignores
// the payload), and a v1.5.4+ client treats a zero-length AUTH_OK from an
// older server as "no advert" (it only parses when payload_size >= 388).
// A v1.5.4 client that predates the signature field will see a longer
// payload, read the leading fields, and -- because it does not verify a
// signature -- this fix is only effective once the signature-verifying
// client (v1.5.5+) is deployed; the server-side signing is harmless to
// older clients.
//
// The advert lets the server drive client auto-update IN-BAND without a
// separate version endpoint: the client compares its own kVersion to
// latest_version (semver) and, if older and download_url is non-empty and
// the signature verifies, fetches the new binary, verifies it against
// sha256, and self-replaces + relaunches. min_version is advisory (the
// server already gates obsolete clients at AUTH via the header flags
// version check); the client surfaces it in the update message. All string
// fields are null-padded ASCII; an all-zero download_url means auto-update
// is disabled (operator has not published a release).
struct AuthOkPayload {   // wire size 388 bytes
    uint8_t latest_version[16];   // ASCII semver of the latest available client (e.g. '1.5.5'), null-padded
    uint8_t min_version[16];   // ASCII semver of the minimum client the pool still serves, null-padded
    uint8_t flags;   // bit0=update_available, bit1=maintenance_active (advisory; authoritative maintenance arrives via the MAINTENANCE message)
    uint8_t reserved[3];   // Zero-filled; reserved for future advert flags/fields
    uint8_t download_url[256];   // HTTPS URL of the latest signed binary, null-padded; all-zero disables auto-update
    uint8_t sha256[32];   // Raw SHA-256 of the binary at download_url; client refuses to install on mismatch
    uint8_t manifest_sig[64];   // v1.5.5 (C3): Ed25519 detached signature over the canonical update manifest (see struct comment). All-zero = unsigned; client refuses to update.
};
static_assert(sizeof(AuthOkPayload) == 388, "AuthOkPayload must be 388 bytes");

// v1.5.4 (protocol_version=4, additive): payload of the MAINTENANCE
// message. Sent server -> client when the pool is in maintenance, either
// immediately after AUTH_OK to a connecting worker or broadcast to all
// live workers when the operator toggles maintenance on at runtime.
//
// active=1 means "back off now"; active=0 is an explicit all-clear that a
// runtime broadcast can use to wake idle workers early (otherwise a client
// simply discovers the all-clear on its next reconnect, since a non-
// maintenance AUTH_OK carries no MAINTENANCE follow-up). retry_after_secs
// is the suggested base reconnect delay (the client jitters it); message
// is a null-padded ASCII operator note shown to the user.
struct MaintenancePayload {   // wire size 262 bytes
    uint8_t active;   // 1=maintenance in effect (back off); 0=all-clear (resume)
    uint8_t reserved;   // Zero-filled; alignment / future flags
    uint32_t retry_after_secs;   // Suggested base reconnect backoff in seconds (client adds jitter)
    uint8_t message[256];   // Operator-facing maintenance note, null-padded ASCII
};
static_assert(sizeof(MaintenancePayload) == 262, "MaintenancePayload must be 262 bytes");

// Server -> client: chunk assignment. The C++ struct in
// jlp_pool_client.hpp is named JLPServerConfig for historical reasons.
// Python side uses jlp_protocol.WorkAssignment.
//
// v1.5 (protocol_version=3): payload grew from 109 to 126 bytes with
// three trailing fields supporting the asymmetric tame/wild work
// assignment. The pre-existing fields (public_key .. work_id) keep
// their identical byte offsets and little-endian encoding so any v3
// decoder that ignored the new tail would still read the head
// correctly; v1.4.x decoders see a 17-byte-too-long payload and
// reject it as malformed. Old/new editions therefore cannot
// accidentally interoperate.
//
// kangaroo_type selects which half of the Pollard rho trail this
// worker contributes. With each worker holding only ONE half, no
// single worker has the data needed to compute the puzzle private
// key locally; the pool server is the sole entity that sees both
// tame and wild distinguished points and is therefore the sole
// key-computer. See .claude/tasks/v1.5-asymmetric-kangaroo.md for
// the full architectural rationale.
//
// start_offset_a / start_offset_b bind this worker to a disjoint
// sub-range of the assignment's [range_start, range_end). The pair
// is interpreted as low 64 bits of an offset window inside the
// chunk: [start_offset_a, start_offset_b). Servers MUST guarantee
// start_offset_b > start_offset_a and that ranges issued to
// same-type workers do not overlap.
struct WorkAssignment {   // wire size 126 bytes
    uint8_t public_key[33];   // Compressed secp256k1 pubkey of the puzzle target
    uint8_t range_start[32];   // Big-endian 32-byte chunk start
    uint8_t range_end[32];   // Big-endian 32-byte chunk end
    uint32_t dp_bits;   // Distinguished-point bit threshold
    uint64_t work_id;   // Low 64 bits of the chunk identifier
    uint8_t kangaroo_type;   // v1.5: 1=TAME_ONLY, 2=WILD_ONLY; 0=BOTH reserved/illegal in pool. Tracks RCKangaroo KANG_MODE_* (third_party/RCKangaroo/defs.h). Distinct from DistinguishedPoint.type byte which encodes 0=tame, 1=wild for a single DP -- the BOTH=0 reservation only applies at WORK_ASN time.
    uint64_t start_offset_a;   // v1.5: inclusive lower bound (low 64 bits) of this worker's assigned offset window inside the chunk
    uint64_t start_offset_b;   // v1.5: exclusive upper bound (low 64 bits) of this worker's assigned offset window inside the chunk
};
static_assert(sizeof(WorkAssignment) == 126, "WorkAssignment must be 126 bytes");

// v1 DP submission. No work_id attestation; server can only do
// cryptographic-math verification, not chunk-binding. Kept for
// backwards compatibility with deployed v1.2.x clients.
struct DistinguishedPoint {   // wire size 66 bytes
    uint8_t x[32];   // Big-endian X coordinate
    uint8_t d[32];   // Big-endian walked distance (22-byte signed extended to 32)
    uint8_t type;   // 0 = tame, 1 = wild
    uint8_t dp_bits;   // Leading-zero bit count required of x
};
static_assert(sizeof(DistinguishedPoint) == 66, "DistinguishedPoint must be 66 bytes");

// v2 DP submission. Adds an 8-byte work_id prefix attesting which
// assigned chunk this DP came from. Server rejects any DP whose
// claimed work_id mismatches the worker's current assignment.
//
// v1.4.1 B.1: gained a 4-byte little-endian sequence field
// between work_id and x. The sequence is a per-(worker, work_id)
// monotonic counter starting at 0 on the first DP of each chunk.
// The server tracks an expected window and rejects out-of-window
// sequences (replays of captured DP_BATCHes, late-arriving
// duplicates from a misbehaving client). Pre-1.4.1 a captured
// DP_BATCH could be replayed an hour later as long as no X
// collided -- no replay defence on the batch level.
struct DistinguishedPointV2 {   // wire size 78 bytes
    uint64_t work_id;   // Chunk id from the assigned WorkAssignment
    uint32_t sequence;   // v1.4.1 B.1: per-(worker, work_id) monotonic seq
    uint8_t x[32];   // Big-endian X coordinate
    uint8_t d[32];   // Big-endian walked distance
    uint8_t type;   // 0 = tame, 1 = wild
    uint8_t dp_bits;   // Leading-zero bit count required of x
};
static_assert(sizeof(DistinguishedPointV2) == 78, "DistinguishedPointV2 must be 78 bytes");

// v1.5.4 DP submission. Superset of v2 (work_id attestation + sequence)
// plus a commitment to the kangaroo walk that produced this DP: a Merkle
// root over the ordered checkpoint distances (one checkpoint every
// CHECKPOINT_INTERVAL jumps) and the committed segment count.
//
// The server later issues a CHALLENGE for K random segments; the worker
// reveals the endpoint checkpoint distances + Merkle proofs (CHALLENGE_RSP,
// variable-length, hand-coded) and the server replays the forward jumps to
// confirm each segment links up. Because the challenge is random and issued
// after commitment, a grinder who fabricated an off-walk distinguished
// point cannot produce a consistent checkpoint chain without actually
// walking -- removing the ~2x advantage of grinding off-walk points.
struct DistinguishedPointV3 {   // wire size 114 bytes
    uint64_t work_id;   // Chunk id from the assigned WorkAssignment
    uint32_t sequence;   // Per-(worker, work_id) monotonic seq (replay defence)
    uint8_t x[32];   // Big-endian X coordinate
    uint8_t d[32];   // Big-endian walked distance
    uint8_t type;   // 0 = tame, 1 = wild
    uint8_t dp_bits;   // Leading-zero bit count required of x
    uint8_t ckpt_root[32];   // Merkle root over the walk's checkpoint distances
    uint32_t n_segments;   // Committed segment count (= checkpoint_count - 1); bounds challenge indices
};
static_assert(sizeof(DistinguishedPointV3) == 114, "DistinguishedPointV3 must be 114 bytes");

// Server -> client periodic stats. your_share is fraction of pool
// DP credit attributable to this worker name (sum across all
// machines using the same name).
struct PoolStats {   // wire size 36 bytes
    uint64_t total_dps;   // Cumulative pool DP count
    uint32_t total_workers;   // Distinct worker names ever seen
    uint32_t active_workers;   // Workers active in last 5 minutes
    float dps_per_second;   // Pool aggregate DP rate
    float your_share;   // Fraction of total_dps attributable to this worker name
    uint64_t your_dps;   // DPs credited to this worker name
    uint32_t uptime_seconds;   // Server uptime in seconds
};
static_assert(sizeof(PoolStats) == 36, "PoolStats must be 36 bytes");

#pragma pack(pop)

} // namespace jlp_wire
} // namespace pool
} // namespace collider
