// =====================================================================
// AUTO-GENERATED -- DO NOT EDIT.
// Generated by tools/codegen/jlp_codegen.py from protocol/jlp.yaml
// IDL hash: 358fc02dc757b24f
// =====================================================================

#pragma once

#include <cstdint>

namespace collider {
namespace pool {
namespace jlp_wire {

constexpr int PROTOCOL_VERSION = 2;

// JLP message header magic
constexpr char MAGIC[4] = {
    0x4b, 0x41, 0x4e, 0x47
};

enum class MessageType : uint8_t {
    AUTH = 0x01,
    AUTH_OK = 0x02,
    AUTH_FAIL = 0x03,
    WORK_REQ = 0x10,
    WORK_ASN = 0x11,
    DP_SUBMIT = 0x20,
    DP_ACK = 0x21,
    DP_BATCH = 0x22,
    DP_SUBMIT_V2 = 0x23,
    DP_BATCH_V2 = 0x24,
    STATS_REQ = 0x30,
    STATS_RSP = 0x31,
    SOLUTION = 0x40,
    PING = 0x50,
    PONG = 0x51,
    MSG_ERROR = 0xff,
};

// Protocol constants
// 1 MB cap to prevent OOM
constexpr uint32_t MAX_MESSAGE_SIZE = 1048576;
// Max DPs per DP_BATCH or DP_BATCH_V2
constexpr uint32_t MAX_BATCH_SIZE = 10000;
// Worker must send AUTH within this window
constexpr uint32_t AUTH_TIMEOUT_SECS = 30;
// Client PING frequency
constexpr uint32_t KEEPALIVE_SECS = 20;

#pragma pack(push, 1)
// Every JLP message starts with this header. MAGIC + type + flags +
// payload_length. Total 8 bytes.
struct Header {   // wire size 8 bytes
    uint8_t magic[4];   // Always "KANG"
    uint8_t type;   // MessageType enum
    uint8_t flags;   // Reserved, currently 0
    uint16_t payload_size;   // Bytes following the header (little-endian)
};
static_assert(sizeof(Header) == 8, "Header must be 8 bytes");

// Worker authentication request. worker_name doubles as the BTC
// payout address; password is the optional pool password (zero-
// filled when none configured). Both fields null-padded.
struct AuthPayload {   // wire size 96 bytes
    uint8_t worker_name[64];   // UTF-8 worker name / BTC address, null-padded
    uint8_t password[32];   // Optional shared pool password, null-padded
};
static_assert(sizeof(AuthPayload) == 96, "AuthPayload must be 96 bytes");

// Server -> client: chunk assignment. The C++ struct in
// jlp_pool_client.hpp is named JLPServerConfig for historical reasons.
// Python side uses jlp_protocol.WorkAssignment.
struct WorkAssignment {   // wire size 109 bytes
    uint8_t public_key[33];   // Compressed secp256k1 pubkey of the puzzle target
    uint8_t range_start[32];   // Big-endian 32-byte chunk start
    uint8_t range_end[32];   // Big-endian 32-byte chunk end
    uint32_t dp_bits;   // Distinguished-point bit threshold
    uint64_t work_id;   // Low 64 bits of the chunk identifier
};
static_assert(sizeof(WorkAssignment) == 109, "WorkAssignment must be 109 bytes");

// v1 DP submission. No work_id attestation; server can only do
// cryptographic-math verification, not chunk-binding. Kept for
// backwards compatibility with deployed v1.2.x clients.
struct DistinguishedPoint {   // wire size 66 bytes
    uint8_t x[32];   // Big-endian X coordinate
    uint8_t d[32];   // Big-endian walked distance (22-byte signed extended to 32)
    uint8_t type;   // 0 = tame, 1 = wild
    uint8_t dp_bits;   // Leading-zero bit count required of x
};
static_assert(sizeof(DistinguishedPoint) == 66, "DistinguishedPoint must be 66 bytes");

// v2 DP submission. Adds an 8-byte work_id prefix attesting which
// assigned chunk this DP came from. Server rejects any DP whose
// claimed work_id mismatches the worker's current assignment.
//
// v1.4.1 B.1: gained a 4-byte little-endian sequence field
// between work_id and x. The sequence is a per-(worker, work_id)
// monotonic counter starting at 0 on the first DP of each chunk.
// The server tracks an expected window and rejects out-of-window
// sequences (replays of captured DP_BATCHes, late-arriving
// duplicates from a misbehaving client). Pre-1.4.1 a captured
// DP_BATCH could be replayed an hour later as long as no X
// collided -- no replay defence on the batch level.
struct DistinguishedPointV2 {   // wire size 78 bytes
    uint64_t work_id;   // Chunk id from the assigned WorkAssignment
    uint32_t sequence;   // v1.4.1 B.1: per-(worker, work_id) monotonic seq
    uint8_t x[32];   // Big-endian X coordinate
    uint8_t d[32];   // Big-endian walked distance
    uint8_t type;   // 0 = tame, 1 = wild
    uint8_t dp_bits;   // Leading-zero bit count required of x
};
static_assert(sizeof(DistinguishedPointV2) == 78, "DistinguishedPointV2 must be 78 bytes");

// Server -> client periodic stats. your_share is fraction of pool
// DP credit attributable to this worker name (sum across all
// machines using the same name).
struct PoolStats {   // wire size 36 bytes
    uint64_t total_dps;   // Cumulative pool DP count
    uint32_t total_workers;   // Distinct worker names ever seen
    uint32_t active_workers;   // Workers active in last 5 minutes
    float dps_per_second;   // Pool aggregate DP rate
    float your_share;   // Fraction of total_dps attributable to this worker name
    uint64_t your_dps;   // DPs credited to this worker name
    uint32_t uptime_seconds;   // Server uptime in seconds
};
static_assert(sizeof(PoolStats) == 36, "PoolStats must be 36 bytes");

#pragma pack(pop)

} // namespace jlp_wire
} // namespace pool
} // namespace collider
