/**
 * Cross-language signing Known-Answer-Test (KAT) — C++ side.
 *
 * The C3 update-manifest and C4 license-assertion canonical byte formats are
 * implemented twice: here in C++ (self_update.cpp build_update_manifest,
 * license_check.cpp canonical_assertion_bytes) and independently in Python/TS
 * (collision-protocol jlp_protocol.py + website license-assertion.ts). Each
 * side used to be tested only against itself, so a silent canonical-byte
 * drift on one side would slip through.
 *
 * This test pins the C++ side to a SHARED, CHECKED-IN fixture living in the
 * sibling collision-protocol repo
 * (collision-protocol/tests/fixtures/signing_kat.json). The matching Python
 * test (collision-protocol/tests/test_signing_kat.py) pins the Python side to
 * the SAME fixture. Both must:
 *   1. reproduce the fixture's `canonical_hex` byte-for-byte, and
 *   2. verify the fixture's `signature_hex` against the fixture's
 *      `test_pubkey_hex` over those canonical bytes.
 * That makes the fixture one ground truth; drift on either side fails that
 * side's own test.
 *
 * The fixture path is injected at configure time via the SIGNING_KAT_FIXTURE
 * compile definition (see CMakeLists.txt). The fixture key is a FIXED TEST key
 * (scripts/gen_signing_kat_fixture.py); only its public half is committed and
 * it is never the production key.
 *
 * Pro-only (canonical_assertion_bytes / ed25519_verify are Pro). On Free
 * builds this compiles to a skip (exit 77).
 */

#ifndef COLLIDER_PRO
int main() { return 77; }   // skip on Free builds
#else

#include "license/license_check.hpp"
#include "runtime/self_update.hpp"

#include <array>
#include <cstdint>
#include <cstdio>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#ifndef SIGNING_KAT_FIXTURE
#error "SIGNING_KAT_FIXTURE (path to signing_kat.json) must be defined by CMake"
#endif

namespace {

int g_failures = 0;

void check(bool cond, const char* what) {
    if (!cond) {
        std::fprintf(stderr, "FAIL: %s\n", what);
        ++g_failures;
    }
}

std::string to_hex(const std::vector<uint8_t>& v) {
    static const char* H = "0123456789abcdef";
    std::string s;
    s.reserve(v.size() * 2);
    for (uint8_t b : v) {
        s.push_back(H[b >> 4]);
        s.push_back(H[b & 0x0F]);
    }
    return s;
}

std::vector<uint8_t> from_hex(const std::string& h) {
    std::vector<uint8_t> out;
    out.reserve(h.size() / 2);
    auto nib = [](char c) -> int {
        if (c >= '0' && c <= '9') return c - '0';
        if (c >= 'a' && c <= 'f') return c - 'a' + 10;
        if (c >= 'A' && c <= 'F') return c - 'A' + 10;
        return -1;
    };
    for (size_t i = 0; i + 1 < h.size(); i += 2) {
        const int hi = nib(h[i]);
        const int lo = nib(h[i + 1]);
        if (hi < 0 || lo < 0) return {};
        out.push_back(static_cast<uint8_t>((hi << 4) | lo));
    }
    return out;
}

// Extract the value of a flat JSON string field `"key": "value"` from the
// fixture text. The fixture is generated by us with json.dumps so the layout
// is stable; we only ever read hex-string / ASCII fields here (no nesting
// ambiguity because every key name we look up is unique in the document).
std::string field(const std::string& doc, const std::string& key) {
    const std::string needle = "\"" + key + "\"";
    size_t k = doc.find(needle);
    if (k == std::string::npos) return "";
    size_t colon = doc.find(':', k + needle.size());
    if (colon == std::string::npos) return "";
    size_t q1 = doc.find('"', colon + 1);
    if (q1 == std::string::npos) return "";
    std::string out;
    bool esc = false;
    for (size_t i = q1 + 1; i < doc.size(); ++i) {
        const char c = doc[i];
        if (esc) {
            // Only the escapes our generator can emit appear here.
            if (c == 'n') out.push_back('\n');
            else if (c == 't') out.push_back('\t');
            else out.push_back(c);
            esc = false;
            continue;
        }
        if (c == '\\') { esc = true; continue; }
        if (c == '"') break;
        out.push_back(c);
    }
    return out;
}

}  // namespace

int main() {
    std::printf("=== cross-language signing KAT (C++ side) ===\n");

    std::ifstream f(SIGNING_KAT_FIXTURE, std::ios::binary);
    if (!f) {
        std::fprintf(stderr,
                     "FAIL: cannot open shared fixture: %s\n",
                     SIGNING_KAT_FIXTURE);
        return 1;
    }
    std::stringstream ss;
    ss << f.rdbuf();
    const std::string doc = ss.str();

    const std::string pub_hex = field(doc, "test_pubkey_hex");
    const std::vector<uint8_t> pub = from_hex(pub_hex);
    check(pub.size() == 32, "fixture pubkey is 32 bytes");

    // --- Update-manifest (C3) ---------------------------------------------
    {
        const std::string latest = field(doc, "latest_version");
        const std::string min_v  = field(doc, "min_version");
        const std::string url    = field(doc, "download_url");
        const std::vector<uint8_t> sha_v = from_hex(field(doc, "sha256_hex"));
        check(sha_v.size() == 32, "fixture sha256 is 32 bytes");
        std::array<uint8_t, 32> sha{};
        for (size_t i = 0; i < 32 && i < sha_v.size(); ++i) sha[i] = sha_v[i];

        const std::vector<uint8_t> rebuilt =
            collider::update::build_update_manifest(latest, min_v, url, sha);
        const std::string expect_hex = field(doc, "canonical_hex");  // first hit = manifest
        check(to_hex(rebuilt) == expect_hex,
              "C++ build_update_manifest matches fixture canonical_hex");

        const std::vector<uint8_t> sig = from_hex(field(doc, "signature_hex"));
        check(sig.size() == 64, "fixture manifest signature is 64 bytes");
        check(collider::license::ed25519_verify(
                  pub.data(), rebuilt.data(), rebuilt.size(),
                  sig.data(), sig.size()),
              "fixture manifest signature verifies over C++-rebuilt bytes");

        // Tamper: one flipped byte must fail.
        std::vector<uint8_t> tampered = rebuilt;
        tampered.back() ^= 0x01;
        check(!collider::license::ed25519_verify(
                  pub.data(), tampered.data(), tampered.size(),
                  sig.data(), sig.size()),
              "manifest signature rejects a tampered byte");
    }

    // --- License assertion (C4) -------------------------------------------
    // Re-extract starting AFTER the manifest block so the second occurrences
    // of canonical_hex / signature_hex (the assertion ones) are read.
    {
        const size_t asrt_off = doc.find("\"license_assertion\"");
        check(asrt_off != std::string::npos, "fixture has license_assertion");
        const std::string asrt_doc =
            asrt_off == std::string::npos ? doc : doc.substr(asrt_off);

        collider::license::LicenseAssertion a;
        a.tier        = field(asrt_doc, "tier");
        a.license_key = field(asrt_doc, "license_key");
        a.machine_id  = field(asrt_doc, "machine_id");
        // Integer fields are bare numbers in JSON; parse them out.
        auto num = [&](const std::string& key) -> long long {
            const std::string nd = "\"" + key + "\"";
            size_t k = asrt_doc.find(nd);
            if (k == std::string::npos) return 0;
            size_t c = asrt_doc.find(':', k + nd.size());
            if (c == std::string::npos) return 0;
            return std::stoll(asrt_doc.substr(c + 1));
        };
        a.expiry_unix = num("expiry_unix");
        a.issued_unix = num("issued_unix");
        a.counter     = num("counter");

        const std::vector<uint8_t> rebuilt =
            collider::license::canonical_assertion_bytes(a);
        const std::string expect_hex = field(asrt_doc, "canonical_hex");
        check(to_hex(rebuilt) == expect_hex,
              "C++ canonical_assertion_bytes matches fixture canonical_hex");

        const std::vector<uint8_t> sig = from_hex(field(asrt_doc, "signature_hex"));
        check(sig.size() == 64, "fixture assertion signature is 64 bytes");
        check(collider::license::ed25519_verify(
                  pub.data(), rebuilt.data(), rebuilt.size(),
                  sig.data(), sig.size()),
              "fixture assertion signature verifies over C++-rebuilt bytes");

        std::vector<uint8_t> tampered = rebuilt;
        tampered[8] ^= 0x01;  // flip tier-length byte
        check(!collider::license::ed25519_verify(
                  pub.data(), tampered.data(), tampered.size(),
                  sig.data(), sig.size()),
              "assertion signature rejects a tampered byte");
    }

    if (g_failures == 0) {
        std::printf("all cross-language signing KAT checks passed\n");
        return 0;
    }
    std::printf("%d cross-language signing KAT check(s) FAILED\n", g_failures);
    return 1;
}

#endif  // COLLIDER_PRO
