/**
 * test_challenge_response -- the v1.5.4 client CHALLENGE_RSP builder produces
 * a payload byte-for-byte identical to the server's
 * JLPProtocol.encode_challenge_rsp, and the Merkle root + proofs it emits
 * verify against the committed root.
 *
 * The expected ROOT and PAYLOAD below were generated by the Python reference
 * (collision-protocol: src.checkpoint_commit.build_root/build_proof +
 * src.jlp_protocol.JLPProtocol.encode_challenge_rsp) on the fixed fixture:
 *   distances = [1, 2, 3, 4]   (32-byte big-endian)
 *   work_id   = 0x1122334455667788
 *   nonce     = 01 02 03 04 05 06 07 08
 *   indices   = [0, 2]
 * Regenerate with:
 *   python -c "from src.checkpoint_commit import build_proof,build_root; \
 *     from src.jlp_protocol import JLPProtocol; d=[1,2,3,4]; \
 *     s=[{'index':i,'d_start':d[i],'d_end':d[i+1], \
 *        'proof_start':build_proof(d,i),'proof_end':build_proof(d,i+1)} \
 *        for i in (0,2)]; \
 *     print(JLPProtocol.encode_challenge_rsp(0x1122334455667788,bytes(range(1,9)),s)[8:].hex())"
 *
 * Exit: 0 pass, 1 fail.
 */

#include "core/checkpoint_commit.hpp"
#include "pool/challenge_response.hpp"

#include <array>
#include <cstdint>
#include <cstdio>
#include <string>
#include <vector>

namespace {

using collider::checkpoint_commit::Distance;
using collider::checkpoint_commit::Hash;

const char* kExpectedRoot =
    "45f385494f9f6116ec5530e7e9e24e2fdf6388c47d72e29657ce7b860c1484c3";

const char* kExpectedPayload =
    "887766554433221101020304050607080200000000000000000000000000000000000000"
    "000000000000000000000000000000000001000000000000000000000000000000000000"
    "000000000000000000000000000202000158cc2f44d3a27866874701fbad573da9ad1cfd"
    "88fa3145531c822f20a58beea101be808de894637e4e4e4f6b169152b682ae0a7a4b050d"
    "ee8be36555b76b6388f90200001fd4247443c9440cb3c48c28851937196bc156032d70a9"
    "6c98e127ecb347e45f01be808de894637e4e4e4f6b169152b682ae0a7a4b050dee8be365"
    "55b76b6388f9020000000000000000000000000000000000000000000000000000000000"
    "000000000003000000000000000000000000000000000000000000000000000000000000"
    "000402000182f02cf2ac0074619e6d747c35e08b29431a16943ddf81cfd9065c004ee636"
    "4a000971c8a1ce81287ccbc95aa4f171a5f807fb13ea2118f56b99769459a64906ad0200"
    "00d9cf8add8675a1b25627d7b0ec33bc177cb3930b0b6e995d79c386b980b2f4d6000971"
    "c8a1ce81287ccbc95aa4f171a5f807fb13ea2118f56b99769459a64906ad";

std::vector<uint8_t> from_hex(const std::string& h) {
    std::vector<uint8_t> out;
    out.reserve(h.size() / 2);
    auto nib = [](char c) -> int {
        if (c >= '0' && c <= '9') return c - '0';
        if (c >= 'a' && c <= 'f') return c - 'a' + 10;
        if (c >= 'A' && c <= 'F') return c - 'A' + 10;
        return -1;
    };
    for (size_t i = 0; i + 1 < h.size(); i += 2)
        out.push_back(static_cast<uint8_t>((nib(h[i]) << 4) | nib(h[i + 1])));
    return out;
}

std::string to_hex(const uint8_t* p, size_t n) {
    static const char* d = "0123456789abcdef";
    std::string s;
    s.reserve(n * 2);
    for (size_t i = 0; i < n; ++i) {
        s.push_back(d[p[i] >> 4]);
        s.push_back(d[p[i] & 0xF]);
    }
    return s;
}

Distance be_distance(uint64_t v) {
    Distance d{};
    for (int i = 0; i < 8; ++i)
        d[31 - i] = static_cast<uint8_t>((v >> (8 * i)) & 0xFF);
    return d;
}

}  // namespace

int main() {
    namespace cc = collider::checkpoint_commit;

    std::vector<Distance> distances = {
        be_distance(1), be_distance(2), be_distance(3), be_distance(4)};
    const uint64_t work_id = 0x1122334455667788ull;
    const std::array<uint8_t, 8> nonce = {1, 2, 3, 4, 5, 6, 7, 8};
    const std::vector<uint32_t> indices = {0, 2};

    // 1. Merkle root matches the Python reference.
    Hash root = cc::build_root(distances);
    if (to_hex(root.data(), 32) != kExpectedRoot) {
        std::fprintf(stderr, "FAIL: root mismatch\n  got %s\n  exp %s\n",
                     to_hex(root.data(), 32).c_str(), kExpectedRoot);
        return 1;
    }

    // 2. CHALLENGE_RSP payload is byte-for-byte the Python wire format.
    std::vector<uint8_t> payload;
    if (!collider::pool::build_challenge_rsp_payload(work_id, nonce, distances,
                                                     indices, payload)) {
        std::fprintf(stderr, "FAIL: build_challenge_rsp_payload returned false\n");
        return 1;
    }
    const std::string got = to_hex(payload.data(), payload.size());
    const std::vector<uint8_t> exp = from_hex(kExpectedPayload);
    if (got != kExpectedPayload) {
        std::fprintf(stderr,
            "FAIL: payload mismatch\n  got(%zu) %s\n  exp(%zu) %s\n",
            payload.size(), got.c_str(), exp.size(), kExpectedPayload);
        return 1;
    }

    // 3. Every emitted proof verifies against the committed root (the check
    //    the server runs before replaying). Build the same proofs and confirm.
    for (uint32_t idx : indices) {
        auto ps = cc::build_proof(distances, idx);
        auto pe = cc::build_proof(distances, idx + 1);
        if (!cc::verify_proof(root, distances[idx], idx, ps)) {
            std::fprintf(stderr, "FAIL: proof_start idx=%u did not verify\n", idx);
            return 1;
        }
        if (!cc::verify_proof(root, distances[idx + 1], idx + 1, pe)) {
            std::fprintf(stderr, "FAIL: proof_end idx=%u did not verify\n", idx + 1);
            return 1;
        }
    }

    // 4. Out-of-range index is rejected (server would replay past the walk).
    std::vector<uint8_t> bad;
    if (collider::pool::build_challenge_rsp_payload(
            work_id, nonce, distances, {3}, bad)) {
        std::fprintf(stderr,
            "FAIL: idx=3 (needs leaf 4, only 0..3 exist) should be rejected\n");
        return 1;
    }

    std::printf("PASS: CHALLENGE_RSP payload matches Python wire format "
                "(%zu bytes), root + proofs verify, OOB rejected.\n",
                payload.size());
    return 0;
}
