#!/usr/bin/env python3
"""
Generate the SOLVED-puzzle entries for src/core/puzzle_config.hpp from
data/puzzle_history.json. Run when puzzle_history.json updates.

Output goes to stdout as a sequence of C++ struct initializers ready
to drop into PuzzleDatabase::get_all(). Unsolved puzzles (whose
addresses aren't derivable from a private key) are NOT generated by
this script -- they stay hand-maintained in puzzle_config.hpp.
"""
from __future__ import annotations
import hashlib
import json
import sys
from pathlib import Path

from coincurve import PublicKey

# Bitcoin address constants. Mainnet P2PKH version byte = 0x00.
P2PKH_VERSION = b"\x00"

ALPHABET = b"123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"


def b58encode(data: bytes) -> str:
    n = int.from_bytes(data, "big")
    out = bytearray()
    while n > 0:
        n, r = divmod(n, 58)
        out.append(ALPHABET[r])
    # Leading zero bytes -> leading '1's
    pad = 0
    for byte in data:
        if byte == 0:
            pad += 1
        else:
            break
    return ("1" * pad) + out[::-1].decode("ascii")


def b58check_encode(payload: bytes) -> str:
    checksum = hashlib.sha256(hashlib.sha256(payload).digest()).digest()[:4]
    return b58encode(payload + checksum)


def hash160(data: bytes) -> bytes:
    sha = hashlib.sha256(data).digest()
    rip = hashlib.new("ripemd160")
    rip.update(sha)
    return rip.digest()


def derive(priv_hex: str) -> tuple[str, str, str]:
    """Returns (compressed_pubkey_hex, hash160_hex, p2pkh_address)."""
    priv = bytes.fromhex(priv_hex.zfill(64))
    pk = PublicKey.from_secret(priv)
    pub_compressed = pk.format(compressed=True)
    h160 = hash160(pub_compressed)
    addr = b58check_encode(P2PKH_VERSION + h160)
    return pub_compressed.hex(), h160.hex(), addr


def main() -> int:
    here = Path(__file__).resolve().parent
    json_path = here.parent / "data" / "puzzle_history.json"
    history = json.loads(json_path.read_text())

    print("// AUTO-GENERATED by scripts/gen_puzzle_table.py from")
    print("// data/puzzle_history.json. DO NOT hand-edit -- regenerate.")
    print()
    for entry in history["solve_history"]:
        n = entry["puzzle_number"]
        priv_hex = entry["private_key_hex"].lower()
        pub_hex, h160_hex, addr = derive(priv_hex)
        # PuzzleInfo: number, bits, address, h160, solved, key, reward, pubkey
        # Solved puzzles report 0.0 reward (the BTC was claimed).
        print(
            f'    {{{n}, {n}, "{addr}", "{h160_hex}", '
            f'true, "0x{priv_hex}", 0.0, "{pub_hex}"}},'
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
